USE ESQLDB;

DELIMITER |
CREATE PROCEDURE RegistrazioneStudente_Piattaforma(IN EMAIL VARCHAR(255), IN PSWD VARCHAR(255), IN NOME VARCHAR(255), IN COGNOME VARCHAR(255), IN TELEFONO INT(10), IN ANNO_IMMATRICOLAZIONE INT(4), IN CODICE VARCHAR(16))
BEGIN
	DECLARE Count_Studente INT DEFAULT 0;
    SET Count_Studente=(SELECT COUNT(*) FROM Studente WHERE (EMAIL_STUDENTE=EMAIL) AND (PSWD_STUDENTE=PSWD));
    IF (Count_Studente=0) THEN 
    	INSERT INTO Utente(EMAIL, PSWD, NOME, COGNOME, TELEFONO) VALUES (EMAIL, PSWD, NOME, COGNOME, TELEFONO);
		INSERT INTO Studente(EMAIL_STUDENTE, PSWD_STUDENTE, ANNO_IMMATRICOLAZIONE, CODICE) VALUES (EMAIL, PSWD, ANNO_IMMATRICOLAZIONE, CODICE);
    END IF;   
END ;
| 
DELIMITER ;

DELIMITER |
CREATE PROCEDURE RegistrazioneDocente_Piattaforma(IN EMAIL VARCHAR(255), IN PSWD VARCHAR(255), IN NOME VARCHAR(255), IN COGNOME VARCHAR(255), IN TELEFONO INT(10), IN NOME_DIPARTIMENTO VARCHAR(255), IN NOME_CORSO VARCHAR(16))
BEGIN
	DECLARE Count_Docente INT DEFAULT 0;
    SET Count_Docente=(SELECT COUNT(*) FROM Docente WHERE (EMAIL_DOCENTE=EMAIL) AND (PSWD_DOCENTE=PSWD));
    IF (Count_Docente=1) THEN 
    	INSERT INTO Utente(EMAIL, PSWD, NOME, COGNOME, TELEFONO) VALUES (EMAIL, PSWD, NOME, COGNOME, TELEFONO);
		INSERT INTO Docemte(EMAIL_DOCENTE, PSWD_DOCENTE, NOME_DIPARTIMENTO, NOME_CORSO) VALUES (EMAIL, PSWD, NOME_DIPARTIMENTO, NOME_CORSO);
    END IF;   
END ;
| 
DELIMITER ;