USE ESQLDB;
DROP TRIGGER IF EXISTS Inserimento_Record;
DROP TRIGGER IF EXISTS Inserimento_Opzione_Risposta;
DROP TRIGGER IF EXISTS Inserimento_Sketch_Codice;
DROP TRIGGER IF EXISTS Update_Stato_Test;
DROP TRIGGER IF EXISTS Cancellazione_Record;
DROP TRIGGER IF EXISTS Cancellazione_Opzione_Risposta;
DROP TRIGGER IF EXISTS Cancellazione_Sketch_Codice;

DELIMITER |
CREATE TRIGGER Inserimento_Record
AFTER INSERT ON Manipolazione_Riga
FOR EACH ROW
    UPDATE Tabella_Esercizio SET NUM_RIGHE=NUM_RIGHE+1 WHERE(ID=NEW.ID_TABELLA);
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER Inserimento_Opzione_Risposta
AFTER INSERT ON Opzione_Risposta
FOR EACH ROW
    UPDATE Quesito SET NUM_RISPOSTE=NUM_RISPOSTE+1 WHERE(ID=NEW.ID_DOMANDA_CHIUSA);
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER Inserimento_Sketch_Codice
AFTER INSERT ON Sketch_Codice
FOR EACH ROW
    UPDATE Quesito SET NUM_RISPOSTE=NUM_RISPOSTE+1 WHERE(ID=NEW.ID_DOMANDA_CODICE);
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER Cancellazione_Record
AFTER DELETE ON Manipolazione_Riga
FOR EACH ROW
    UPDATE Tabella_Esercizio SET NUM_RIGHE=NUM_RIGHE-1 WHERE(ID=OLD.ID_TABELLA);
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER Cancellazione_Opzione_Risposta
AFTER DELETE ON Opzione_Risposta
FOR EACH ROW
    UPDATE Quesito SET NUM_RISPOSTE=NUM_RISPOSTE-1 WHERE(ID=OLD.ID_DOMANDA_CHIUSA);
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER Cancellazione_Sketch_Codice
AFTER DELETE ON Sketch_Codice
FOR EACH ROW
    UPDATE Quesito SET NUM_RISPOSTE=NUM_RISPOSTE-1 WHERE(ID=OLD.ID_DOMANDA_CODICE);
|
DELIMITER ;